"""Removed loja relation on vendas v5

Revision ID: 02fa54de42ac
Revises: f2e91437cfd3
Create Date: 2022-07-19 18:21:07.575491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02fa54de42ac'
down_revision = 'f2e91437cfd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendas', sa.Column('id_loja', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vendas', 'lojas', ['id_loja'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendas', type_='foreignkey')
    op.drop_column('vendas', 'id_loja')
    # ### end Alembic commands ###