"""Vendas model created v3

Revision ID: 05641ef112b4
Revises: ee8ae6c9d280
Create Date: 2022-07-19 15:13:25.971650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05641ef112b4'
down_revision = 'ee8ae6c9d280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('loja_id', sa.Integer(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('programa_pontos_id', sa.Integer(), nullable=True),
    sa.Column('preco_venda', sa.Float(), nullable=True),
    sa.Column('frete', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['loja_id'], ['lojas.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['programa_pontos_id'], ['programas_pontos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendas_created_at'), 'vendas', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendas_created_at'), table_name='vendas')
    op.drop_table('vendas')
    # ### end Alembic commands ###