"""Add one-to-many relationship vendas e loja

Revision ID: 087b124aab44
Revises: 2612283999e2
Create Date: 2022-07-20 01:06:33.899714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087b124aab44'
down_revision = '2612283999e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendas', sa.Column('id_loja', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vendas', 'lojas', ['id_loja'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendas', type_='foreignkey')
    op.drop_column('vendas', 'id_loja')
    # ### end Alembic commands ###