"""Removed loja relation on vendas

Revision ID: 1622a5016f98
Revises: f566b789eb9c
Create Date: 2022-07-19 17:11:53.710746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1622a5016f98'
down_revision = 'f566b789eb9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lojas_venda')
    op.drop_constraint('vendas_id_loja_fkey', 'vendas', type_='foreignkey')
    op.drop_column('vendas', 'id_loja')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendas', sa.Column('id_loja', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('vendas_id_loja_fkey', 'vendas', 'lojas', ['id_loja'], ['id'])
    op.create_table('lojas_venda',
    sa.Column('id_venda', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_loja', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_loja'], ['lojas.id'], name='lojas_venda_id_loja_fkey'),
    sa.ForeignKeyConstraint(['id_venda'], ['vendas.id'], name='lojas_venda_id_venda_fkey')
    )
    # ### end Alembic commands ###