"""Add one-to-one relationship vendas e produtos

Revision ID: 2612283999e2
Revises: 5a7fc9aa02bd
Create Date: 2022-07-20 00:07:33.233968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2612283999e2'
down_revision = '5a7fc9aa02bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###