"""Removed loja relation on vendas v2

Revision ID: 4b132d973468
Revises: 1622a5016f98
Create Date: 2022-07-19 17:18:19.146398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b132d973468'
down_revision = '1622a5016f98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###