"""Usuario model fix to unique email

Revision ID: 4d0a033f7bb8
Revises: 792c80521816
Create Date: 2022-07-14 17:55:40.290458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d0a033f7bb8'
down_revision = '792c80521816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    # ### end Alembic commands ###