"""Removed columns id_loja and id_programa_pontos on table vendas

Revision ID: 5a7fc9aa02bd
Revises: 9a761a60205c
Create Date: 2022-07-19 23:12:41.438653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a7fc9aa02bd'
down_revision = '9a761a60205c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('vendas_id_loja_fkey', 'vendas', type_='foreignkey')
    op.drop_constraint('vendas_id_loja_programa_pontos_fkey', 'vendas', type_='foreignkey')
    op.drop_column('vendas', 'id_loja')
    op.drop_column('vendas', 'id_loja_programa_pontos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendas', sa.Column('id_loja_programa_pontos', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vendas', sa.Column('id_loja', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('vendas_id_loja_programa_pontos_fkey', 'vendas', 'loja_programa_pontos', ['id_loja_programa_pontos'], ['id'])
    op.create_foreign_key('vendas_id_loja_fkey', 'vendas', 'lojas', ['id_loja'], ['id'])
    # ### end Alembic commands ###