"""Inserted column valor_bonus in loja_programa_pontos table

Revision ID: 6401471f7bcc
Revises: 4d0a033f7bb8
Create Date: 2022-07-18 15:20:33.751487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6401471f7bcc'
down_revision = '4d0a033f7bb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loja_programa_pontos', sa.Column('valor_bonus', sa.Float(), nullable=False))
    op.add_column('loja_programa_pontos', sa.Column('valor_real', sa.Float(), nullable=False))
    op.drop_column('loja_programa_pontos', 'preco_por_real')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loja_programa_pontos', sa.Column('preco_por_real', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('loja_programa_pontos', 'valor_real')
    op.drop_column('loja_programa_pontos', 'valor_bonus')
    # ### end Alembic commands ###