"""Vendas model created and relationships

Revision ID: 78cd64253827
Revises: f0a0a8e04631
Create Date: 2022-07-19 14:35:18.514163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78cd64253827'
down_revision = 'f0a0a8e04631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###