"""Add one-to-many to test with LojaProgramaPontos

Revision ID: 7bca7adc799b
Revises: 087b124aab44
Create Date: 2022-07-20 01:32:31.464067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bca7adc799b'
down_revision = '087b124aab44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###