"""Size value columns url

Revision ID: 8802a61497eb
Revises: f56e26efe8cb
Create Date: 2022-07-14 00:12:08.809167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8802a61497eb'
down_revision = 'f56e26efe8cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###