"""Remove unique required column name ProgramaPontos

Revision ID: 90e597b2c430
Revises: 7bca7adc799b
Create Date: 2022-07-20 15:00:45.787352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90e597b2c430'
down_revision = '7bca7adc799b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('programas_pontos_nome_key', 'programas_pontos', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('programas_pontos_nome_key', 'programas_pontos', ['nome'])
    # ### end Alembic commands ###