"""Removed loja relation on vendas v3

Revision ID: 9dab920f8c92
Revises: 4b132d973468
Create Date: 2022-07-19 17:28:20.900186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dab920f8c92'
down_revision = '4b132d973468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('vendas_id_loja_programa_pontos_fkey', 'vendas', type_='foreignkey')
    op.drop_constraint('vendas_id_produto_fkey', 'vendas', type_='foreignkey')
    op.drop_column('vendas', 'id_produto')
    op.drop_column('vendas', 'id_loja_programa_pontos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendas', sa.Column('id_loja_programa_pontos', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vendas', sa.Column('id_produto', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('vendas_id_produto_fkey', 'vendas', 'produtos', ['id_produto'], ['id'])
    op.create_foreign_key('vendas_id_loja_programa_pontos_fkey', 'vendas', 'loja_programa_pontos', ['id_loja_programa_pontos'], ['id'])
    # ### end Alembic commands ###