"""Vendas model created

Revision ID: b277a3894adf
Revises: 78cd64253827
Create Date: 2022-07-19 15:02:43.459204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b277a3894adf'
down_revision = '78cd64253827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###