"""Resgate model created

Revision ID: d38a2c0e6bdc
Revises: 8802a61497eb
Create Date: 2022-07-14 10:12:55.988113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd38a2c0e6bdc'
down_revision = '8802a61497eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resgates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('product_sku', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=350), nullable=False),
    sa.Column('product_reedem', sa.Float(), nullable=False),
    sa.Column('product_url', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resgates_created_at'), 'resgates', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resgates_created_at'), table_name='resgates')
    op.drop_table('resgates')
    # ### end Alembic commands ###