"""Changes in LojaProgramaPontos

Revision ID: e2257fae6e22
Revises: 6401471f7bcc
Create Date: 2022-07-18 19:42:17.824865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2257fae6e22'
down_revision = '6401471f7bcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loja_programa_pontos', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('loja_programa_pontos', sa.Column('id_programa_pontos', sa.Integer(), nullable=True))
    op.drop_index('ix_loja_programa_pontos_CreatedAt', table_name='loja_programa_pontos')
    op.create_index(op.f('ix_loja_programa_pontos_created_at'), 'loja_programa_pontos', ['created_at'], unique=False)
    op.drop_constraint('loja_programa_pontos_id_programas_pontos_fkey', 'loja_programa_pontos', type_='foreignkey')
    op.create_foreign_key(None, 'loja_programa_pontos', 'programas_pontos', ['id_programa_pontos'], ['id'])
    op.drop_column('loja_programa_pontos', 'id_programas_pontos')
    op.drop_column('loja_programa_pontos', 'CreatedAt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loja_programa_pontos', sa.Column('CreatedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('loja_programa_pontos', sa.Column('id_programas_pontos', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'loja_programa_pontos', type_='foreignkey')
    op.create_foreign_key('loja_programa_pontos_id_programas_pontos_fkey', 'loja_programa_pontos', 'programas_pontos', ['id_programas_pontos'], ['id'])
    op.drop_index(op.f('ix_loja_programa_pontos_created_at'), table_name='loja_programa_pontos')
    op.create_index('ix_loja_programa_pontos_CreatedAt', 'loja_programa_pontos', ['CreatedAt'], unique=False)
    op.drop_column('loja_programa_pontos', 'id_programa_pontos')
    op.drop_column('loja_programa_pontos', 'created_at')
    # ### end Alembic commands ###