"""Vendas model created

Revision ID: ee8ae6c9d280
Revises: b277a3894adf
Create Date: 2022-07-19 15:07:39.893009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee8ae6c9d280'
down_revision = 'b277a3894adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###