"""Many to Many LojaProgramaPontos

Revision ID: f0a0a8e04631
Revises: e2257fae6e22
Create Date: 2022-07-18 23:58:52.803297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0a0a8e04631'
down_revision = 'e2257fae6e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###