"""Removed loja relation on vendas v4

Revision ID: f2e91437cfd3
Revises: 9dab920f8c92
Create Date: 2022-07-19 17:32:18.318179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e91437cfd3'
down_revision = '9dab920f8c92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendas', sa.Column('id_produto', sa.Integer(), nullable=True))
    op.add_column('vendas', sa.Column('id_loja_programa_pontos', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vendas', 'produtos', ['id_produto'], ['id'])
    op.create_foreign_key(None, 'vendas', 'loja_programa_pontos', ['id_loja_programa_pontos'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendas', type_='foreignkey')
    op.drop_constraint(None, 'vendas', type_='foreignkey')
    op.drop_column('vendas', 'id_loja_programa_pontos')
    op.drop_column('vendas', 'id_produto')
    # ### end Alembic commands ###