"""Vendas recreated relationships

Revision ID: f566b789eb9c
Revises: 05641ef112b4
Create Date: 2022-07-19 16:46:46.142583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f566b789eb9c'
down_revision = '05641ef112b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loja_programa_pontos_venda',
    sa.Column('id_venda', sa.Integer(), nullable=True),
    sa.Column('id_loja_programa_pontos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_loja_programa_pontos'], ['loja_programa_pontos.id'], ),
    sa.ForeignKeyConstraint(['id_venda'], ['vendas.id'], )
    )
    op.create_table('lojas_venda',
    sa.Column('id_venda', sa.Integer(), nullable=True),
    sa.Column('id_loja', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_loja'], ['lojas.id'], ),
    sa.ForeignKeyConstraint(['id_venda'], ['vendas.id'], )
    )
    op.create_table('produtos_venda',
    sa.Column('id_venda', sa.Integer(), nullable=True),
    sa.Column('id_produto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_produto'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['id_venda'], ['vendas.id'], )
    )
    op.add_column('vendas', sa.Column('id_loja', sa.Integer(), nullable=True))
    op.add_column('vendas', sa.Column('id_produto', sa.Integer(), nullable=True))
    op.add_column('vendas', sa.Column('id_loja_programa_pontos', sa.Integer(), nullable=True))
    op.drop_constraint('vendas_loja_id_fkey', 'vendas', type_='foreignkey')
    op.drop_constraint('vendas_programa_pontos_id_fkey', 'vendas', type_='foreignkey')
    op.drop_constraint('vendas_produto_id_fkey', 'vendas', type_='foreignkey')
    op.create_foreign_key(None, 'vendas', 'loja_programa_pontos', ['id_loja_programa_pontos'], ['id'])
    op.create_foreign_key(None, 'vendas', 'lojas', ['id_loja'], ['id'])
    op.create_foreign_key(None, 'vendas', 'produtos', ['id_produto'], ['id'])
    op.drop_column('vendas', 'produto_id')
    op.drop_column('vendas', 'loja_id')
    op.drop_column('vendas', 'programa_pontos_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendas', sa.Column('programa_pontos_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vendas', sa.Column('loja_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('vendas', sa.Column('produto_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vendas', type_='foreignkey')
    op.drop_constraint(None, 'vendas', type_='foreignkey')
    op.drop_constraint(None, 'vendas', type_='foreignkey')
    op.create_foreign_key('vendas_produto_id_fkey', 'vendas', 'produtos', ['produto_id'], ['id'])
    op.create_foreign_key('vendas_programa_pontos_id_fkey', 'vendas', 'programas_pontos', ['programa_pontos_id'], ['id'])
    op.create_foreign_key('vendas_loja_id_fkey', 'vendas', 'lojas', ['loja_id'], ['id'])
    op.drop_column('vendas', 'id_loja_programa_pontos')
    op.drop_column('vendas', 'id_produto')
    op.drop_column('vendas', 'id_loja')
    op.drop_table('produtos_venda')
    op.drop_table('lojas_venda')
    op.drop_table('loja_programa_pontos_venda')
    # ### end Alembic commands ###