"""Add shopmilhas table

Revision ID: f56e26efe8cb
Revises: 71241a9973ee
Create Date: 2022-07-13 18:38:43.539528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f56e26efe8cb'
down_revision = '71241a9973ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopmilhas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('product_sku', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=250), nullable=False),
    sa.Column('product_price_sale', sa.Float(), nullable=False),
    sa.Column('product_gain_miles', sa.Float(), nullable=False),
    sa.Column('product_url', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopmilhas_created_at'), 'shopmilhas', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopmilhas_created_at'), table_name='shopmilhas')
    op.drop_table('shopmilhas')
    # ### end Alembic commands ###