from models.loja_model import LojaModel
from models.produto_model import ProdutoModel
from models.programa_pontos_model import ProgramaPontosModel
from models.shop_milhas_model import ShopMilhasModel
from models.resgate_model import ResgateModel
from models.usuario_model import UsuarioModel